exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor
- bundle
- node_modules
- .github
- "*.iml"
- fetch_yt_preview
- README.md
- Taskfile.yaml

highlighter: rouge
markdown: kramdown

external: https://octoprint.org
baseurl: ""

title : OctoPrint.org
tagline: The snappy web interface for your 3D printer.
description: OctoPrint is the snappy web interface for your 3D printer that allows you to control and monitor all aspects of your printer and print jobs, right from your browser.

paginate: 10
paginate_path: "/blog/page:num/"

repository: OctoPrint/OctoPrint

permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!-- more -->

author:
  name: Gina Häußge
  twitter: foosel

patreon: https://patreon.com/foosel
paypal_me: https://paypal.me/octoprint3d
paypal_mail: funding&#64;octoprint&#46;org
liberapay: https://liberapay.com/foosel/donate
donorbox_regularly: https://donorbox.org/support-octoprint?recurring=true
donorbox_once: https://donorbox.org/support-octoprint
github_sponsors: https://github.com/users/foosel/sponsorship

sourcerepo: https://github.com/OctoPrint/OctoPrint
forum: https://community.octoprint.org
discord: https://discord.octoprint.org
irc: ircs://irc.libera.chat:6697/#octoprint

carbon: //cdn.carbonads.com/carbon.js?serve=CKYIL53W&placement=octoprintorg

twitter: OctoPrint3D
mastodon: "@octoprint@fosstodon.org"
facebook: OctoPrint
youtube: OctoPrint3D

twitterlink: https://twitter.com/OctoPrint3D
mastodonlink: https://fosstodon.org/@octoprint
facebooklink: https://facebook.com/OctoPrint
youtubelink: https://www.youtube.com/c/OctoPrint3D

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

