permalink: /blog/:year/:month/:day/:title 

exclude:
- CNAME
- Gemfile
- Gemfile.lock
- vendor
- "*.iml"
- fetch_yt_preview

highlighter: rouge
markdown: kramdown

external: https://octoprint.org
#external: http://192.168.1.3:4000
baseurl: ""

title : OctoPrint.org
tagline: The snappy web interface for your 3D printer.
description: OctoPrint is the snappy web interface for your 3D printer that allows you to control and monitor all aspects of your printer and print jobs, right from your browser.

paginate: 10
paginate_path: "/blog/page:num/"

permalink: /blog/:year/:month/:day/:title/
excerpt_separator: <!-- more -->

author:
  name: Gina Häußge
  twitter: foosel

patreon: https://patreon.com/foosel
paypal: https://paypal.me/foosel
liberapay: https://liberapay.com/foosel/donate
donorbox_regularly: https://donorbox.org/support-octoprint?recurring=true
donorbox_once: https://donorbox.org/support-octoprint
sourcerepo: https://github.com/foosel/OctoPrint

carbon: //cdn.carbonads.com/carbon.js?serve=CKYIL53W&placement=octoprintorg

twitter: OctoPrint3D
facebook: OctoPrint
gplus: OctoPrintOrg

twitterlink: https://twitter.com/OctoPrint3D
facebooklink: https://facebook.com/OctoPrint
gpluslink: https://plus.google.com/+OctoprintOrg/posts

gems: [jekyll-paginate]