baseURL = 'https://octoprint.org/'
locale = 'en-us'
title = 'OctoPrint'

theme = "liftoff"

enableRobotsTXT = true
enableEmoji = false

[pagination]
  pagerSize = 6

[params]
  description = ""
  tagline = "Your printer. Your rules."
  accent = "octoprint"
  copyrightOwner = "Gina Häußge"
  copyrightSuffix = """
"""
  legalFooter = """
"OctoPrint" is a [registered trademark](/trademark-rules) &middot;
[Imprint](/imprint) &middot;
[Privacy Policy](/privacy)
"""
  
  carbon = "//cdn.carbonads.com/carbon.js?serve=CKYIL53W&placement=octoprintorg"

#[params.repo]
#  host  = "github"
#  owner = "OctoPrint"
#  name  = "OctoPrint"

[[params.social]]
  icon = "simple-icons:github"
  name = "GitHub"
  url  = "https://octoprint.org/OctoPrint"

[[params.social]]
  icon = "simple-icons:discourse"
  name = "Forum"
  url  = "https://community.octoprint.org"

[[params.social]]
  icon = "simple-icons:discord"
  name = "Discord"
  url  = "https://discord.octoprint.org"

[[params.social]]
  icon = "simple-icons:mastodon"
  name = "Mastodon"
  url  = "https://floss.social/@OctoPrint"

[[params.social]]
  icon = "mdi:rss"
  name = "RSS"
  url  = "/index.xml"

[menus]
  [[menus.main]]
    name    = "Blog"
    pageRef = "/blog"
    weight  = 20

  [[menus.main]]
    name    = "Get Help"
    pageRef = "/help"
    weight  = 30

  [[menus.main]]
    name    = "Download"
    pageRef = "/download"
    weight  = 40

  [[menus.main]]
    name    = "Donate"
    pageRef = "/support"
    weight  = 50

  [[menus.main]]
    name    = "Merchandise"
    pageRef = "/merch"
    weight  = 60


  [[menus.footer]]
    identifier = "links"
    name = "On the web"
    weight = 10

  [[menus.footer]]
    parent = "links"
    name = "YouTube"
    url = "https://www.youtube.com/c/OctoPrint3D"
    weight = 10

  [[menus.footer]]
    parent = "links"
    name = "Status"
    url = "https://status.octoprint.org/"
    weight = 20

  [[menus.footer]]
    identifier = "legal"
    name = "Legal"
    weight = 20

  [[menus.footer]]
    parent = "legal"
    name = "Code of Conduct"
    url = "/coc"

  [[menus.footer]]
    parent = "legal"
    name = "Security Policy"
    url = "/security"

  [[menus.footer]]
    parent = "legal"
    name = "Imprint"
    url = "/imprint"

  [[menus.footer]]
    parent = "legal"
    name = "Privacy Policy"
    url = "/privacy"

  [[menus.footer]]
    parent = "legal"
    name = "Trademark rules"
    url = "/trademark-rules"

[markup]
  [markup.highlight]
    style = "github-dark"
    noClasses = true
    lineNos = false
    codeFences = true
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
