version: "3"

tasks:
  install:
    desc: Install dependencies
    cmds:
      - |
        bundle install

  serve:
    desc: Serve page on localhost:4000
    cmds:
      - |
        bundle exec jekyll s --future

  assets:
    desc: Update CSS assets
    cmds:
      - |
        lessc "--clean-css=--s1 --advanced --compatibility=ie8" assets/less/site.less assets/css/site.css

  yt-preview:
    desc: Fetch YouTube Preview pictures
    cmds:
      - |
        ./fetch_yt_preview

  ### CI related

  ci-update:
    desc: Update GitHub Action workflow files to new versions of used actions
    cmds:
      - npx actions-up --include-branches
